-- Mauricio López Cházaro
-- 210804 - 449 457 72 48
-- mauricioeneltrabajo@gmail.com

-- 2023/09/18

-- Admin role
DROP ROLE IF EXISTS qaKdQa5ygYm3YCk9uaPhpqdEXnGAcibGKQmXzKEiNPwS2ujyx9Sc8SSijv3LjBL;

CREATE ROLE qaKdQa5ygYm3YCk9uaPhpqdEXnGAcibGKQmXzKEiNPwS2ujyx9Sc8SSijv3LjBL
CONNECTION LIMIT 25
PASSWORD 'ZH9SNtLouSwPnt3wXnMeZyXCw9dbZsQVUFQkAnfzQtabSUUw5EkzyVSs3jJUDNx';

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM qaKdQa5ygYm3YCk9uaPhpqdEXnGAcibGKQmXzKEiNPwS2ujyx9Sc8SSijv3LjBL;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM qaKdQa5ygYm3YCk9uaPhpqdEXnGAcibGKQmXzKEiNPwS2ujyx9Sc8SSijv3LjBL;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM qaKdQa5ygYm3YCk9uaPhpqdEXnGAcibGKQmXzKEiNPwS2ujyx9Sc8SSijv3LjBL;
